module.exports = {
	'likes': '{ likes, number } me gusta',
	'logout': 'Salir',
	'english': 'ingles',
	'spanish': 'espanol',
	'signup.subheading': 'Regístrate para ver fotos de tus amigos estudiando en Platzi',
	'signup.facebook': 'iniciar sesion con facebook',
	'signup.text': 'Iniciar sesion',
	'email': 'Correo electronico',
	'username': 'Nombre de Usuario',
	'fullname': 'Nombre completo',
	'password': 'Contrasena',
	'signup.call-to-action': 'Registrate',
	'signup.have-account': 'Tienes una cuenta?',
	'signin': 'Entrar', 
	'signin.not-have-account': 'No tienes una cuenta?',
	'language': 'idioma',
	'upload-picture': 'subir foto',
	'upload': 'subir'
}